cd /media/phil/titanBU/borgBU/
l
vim README 
cd
cd .config/
l
vim user-dirs.dirs 
cd
manvim setfont
type sfdisk
sfdisk --help
sfdisk -v
type cfdisk
cfdisk --help
cfdisk -V
type util-linux
show util-linux
show meson
show ninja
show ninja-build
type pip3
cd dev/
git clone https://github.com/mesonbuild/meson.git
cd meson/
l
cd ../
l
git clone git://github.com/ninja-build/ninja.git && cd ninja
git checkout release
g?
l
cd
ip a l
ip ro l
cd Documents/
l
cd
apt-file search zramctl
show apt-file
_ apt install apt-file
_ apt-file update
apt-file search zramctl
l
type s3cmd
cd bin/
l
cd
apt list --upgradable
vim
l
ls++ -a
l
cd bin/
l
cd S3/
l
cd ..
l
cd GitExtensions/
l
cd ..
rm -rf GitExtensions
l
cd Nocturn-linux-x64/
l
cd ..
cd
type toast
l
l
ps aux | grep odrive
cd
ls++ -a
l
l
l
l
ps aux | grep odrive
byobu-tmux
l
ls++ -a
ls++ -a
l
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
top
l
byobu --help
cd dev/
git clone https://github.com/CISOfy/lynis.git
cd lynis/
l
ll
./lynis audit system
l
_ cp /tmp/lynis.log ~/
cd
l
vim lynis.log 
ll
_ chown phil:phil lynis.log 
ll
vim lynis.log 
_ cp /tmp/lynis-report.dat ~/
_ chown phil:phil lynis-report.dat 
vim lynis-report.dat 
l
mv lynis.log lynis300917.log
mv lynis-report.dat lynis-report309017.dat
l
mv lynis-report309017.dat lynis-report300917.dat
l
mv lynis300917.log lynis-report300917.dat logs-nmap/
l
lynis show details TEST-ID
cd /var/log
l
cd /tmp/
l
cd /etc/
l
cd ssh/
l
vim sshd_config 
_ vim sshd_config 
cd
ps aux | grep odrive
type apt-transport-https
show apt-transport-https
cd /etc/aide/
l
vim aide.conf
cd
_ find / -name aide -print 2>/dev/null 
cd /var/log/aide/
l
vim aide.log
cd /var/lib/aide/
l
vim aide.conf.autogenerated 
_ vim aide.conf.autogenerated 
cd
aide --help
_ vim /etc/aide/aide.conf
_ aide --config-check
aide --config-check
aide -i
_ aide -i
cd /var/lib/aide/
l
ll
cd
aide -C
_ find / -name aide.db -print 2>/dev/null 
aideinit
_ aideinit
cd /var/lib/aide/
l
ll
cd
_ grep "aide.conf" /etc/cron.daily/aide
cd /var/log/aide/
l
vim aide.log
cd
ls++ -a
cd /etc/aide/
l
cd
ps aux | grep odrive
ip
cd bin/Nocturn-linux-x64/
l
./Nocturn 
cd bin/firefox/
l
./firefox-bin 
ls++ -a
l
ls++ -a
ls++ -a
top
l
ps aux | grep aide
ip
l
show python-markups
cd Downloads/
l
mv Drving_License_Number horse-latitudes_co_uk_ee.crt ~/vim_files/
_ gdebi remarkable_1.87_all.deb 
cd
l
cd -
l
mv haroopad-v0.13.1-x64.deb remarkable_1.87_all.deb ~/src/
l
cd
mv s3cmd-commands.md vim_files/
cd bin/
l
cd
cd dev/
cd vim
l
git pull
byobu-tmux
l
ls++ -a
l
cd dev/
git clone https://github.com/jgm/gitit.git
cd
type ikiwiki
show ikiwiki
show python-docutils
byobu-tmux
l
ls++ -a
ls++ -a
cd bin/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
l
cd scripts/
l
cd bak/
l
ll
cd
ps aux | grep odrive
cd /media/phil/
l
cd 0D59-AFCF/
ll
touch test
ll
cd
cp -r vim_files /media/phil/0D59-AFCF/
cd -
ll
cd vim_files/
l
ll
cd cover/
l
cd ../../
l
ll
cd ~/.ssh/
l
ll
cd
cd /media/phil/0D59-AFCF/
l
mkdir kerberosSSHKeys
ll
cd
cp -r ~/.ssh /media/phil/0D59-AFCF/kerberosSSHKeys/
cd -
cd kerberosSSHKeys/
ll
cd .ssh/
l
cd
cd vim_files/
l
cd .ssh/
ll
cd ~/.ssh/
ll
vim authorized_keys 
cd
vim
cd /usr/share/dict
l
readlink words
cd /etc/dictionaries-common/
l
readlink words
cd /usr/share/
l
cd /usr/share/dict/
l
readlink words
vim README.select-wordlist 
cd
cd /etc/mail
ping 224.0.0.251
cd dev/
git clone https://github.com/kennethreitz/saythanks.io.git
cd saythanks.io/
l
cd saythanks/
l
cd templates/
l
cd ..
cd static/
l
cd images/
l
cd ../../../../
l
cd
df -h
l
ifconfig
top
ps aux | grep python
ps aux | grep ruby
l
l
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
cd .mono/
l
cd registry/
l
cd CurrentUser/
l
cd software/
l
cd gitextensions/
l
cd ../../../../
du -ach
cd
ping 8.8.8.8
ping 127.0.0.1
ip
ping 192.168.1.163
l
cd .local/share/
l
ll
cd
cd /media/phil/titanBU/FWkerberos/
ll
cd 2017-10-04_14.43.44.242786.kerberos.ful/
ll
vim sbackup.2017-10-04_14.43.44.159090.log 
cd
str='this is a message'
strlen=${#str}
echo "${str:4:strlen}"
ls++ -a
ls++ -a
top
l
top
l
ls++ -a
cd bin/firefox/
./firefox-bin 
cd dev/firefox/
./firefox-bin 
cd bin/firefox/
./firefox-bin 
_ apt update
ps aux | grep apt
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
l
l
uname -r
cd .config/git
l
vim
wc KiplingBoris.txt 
wc --help
wc -m KiplingBoris.txt 
cd src/
l
cd ~/Downloads/
l
tar xvf firefox-57.0b5.tar.bz2 
l
mv firefox-57.0b5.tar.bz2 ~/src/
mv firefox ~/dev/
cd ~/dev/
cd firefox/
l
cd
du -ach
cd dev/firefox/
du -ach
l
cd browser/
l
cd chrome/
l
cd ../../../
l
cd
vbrc
type toast
cd .toast/armed/bin/
l
readlink toast
cd
cd .toast/
l
cd pkg/
l
cd toast/
l
cd v1.488/1/root/
l
cd bin/
l
ll
vim toast 
cd
rvm --version
rvm --help
rvm get stable
gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
rvm get stable
rvm list known
ruby -v
perlbrew available
uname -r
type ex
ex
ex --help
_ apt update
_ apt upgrade
_ systemctl status dbus.service
cd /lib/systemd/system/
l
_ vim dbus.service 
cd
cd -
cd ../
l
cd system
l
cd
git --version
type git
cd /usr/bin/
l
readlink nawk
cd
git --help
cd dev/vim
git pull
vim src/version.c
cd
git help log
git help git-config
git help help
git help -g
git help everyday
top
l
top
l
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
mv KiplingBoris.txt sigs/
type tmux
tmux --version
tmux -v
tmux -V
cd Downloads/
l
_ gdebi python3-multibootusb_8.8.0-1_all.deb 
l
mv python3-multibootusb_8.8.0-1_all.deb ~/src/
tar zxvf tmux-2.6.tar.gz 
mv tmux-2.6.tar.gz ~/src/
cd tmux-2.6/
l
vim README 
cd
nroff -mdoc tmux.1|less
manvim tmux
cd /etc/
l
cd apt
l
cd /var/log/apt/
l
vim history.log
cd
cd /media/phil/
l
cd Ubuntu-GNOME\ 17.04\ amd64/
l
cd casper/
l
cd
l
vim tmux-client-28222.log 
mv tmux-client-28222.log logs-nmap/
show compizconfig-settings-manager
_ apt install compizconfig-settings-manager
ls++ -a
l
top
l
ssh phil@owncloud.org.uk
ls++ -a
ls++ -a
top
ps aux | grep compiz
top
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
l
ifconfig
awk 1 /dev/null 
type gawk
gawk --version
whereis gawk
awk --version
whereis awk
id -G
id -Gn
ls++ -a
ls++ -a
l
ls++ -a
l
l
cd dev/firefox/
./firefox-bin 
_ apt update
byobu-tmux
ls++ -a
top
ps aux | grep zombie
l
cd /media/phil/titanBU/borgBU/
l
du -ach
vim README 
cd
cd -
cd ../
l
cd
borgb list /media/phil/titanBU/borgBU/
journalctl --help
cd /run/
l
cd log
l
cd ../
cd systemd/
l
cd journal/
l
ll
cd ../../
ll
cd
type borgbackup
borgbackup --version
show borgbackup
cd Downloads/
l
rm Sia-UI-v1.3.0-linux-x64.zip 
vim README.txt 
gpg --verify borg-linux64.asc borg-linux64
l
cd
gpg --help
gpg --import tw@waldmann-edv.de
gpg --search tw@waldmann-edv.de
gpg --keyserver tw@waldmann-edv.de
cd Downloads/
l
gpg --verify borg-linux64.asc borg-linux64
gpg --list-keys
l
gpg --verify borg-linux64.asc borg-linux64
gpg --help
l
rm Thomas\ Waldmann.pgp 
gpg --verify borg-linux64.asc borg-linux64
l
rm borg-linux64.asc 
l
chmod 755 borg-linux64 
l
mv borg-linux64 ~/bin/
mv README.txt borgbackupREADME.txt
l
mv borgbackupREADME.txt ~/vim_files/
l
cd
type borgbackup
~/bin/borgbackup
cd Downloads/
l
cd ~/bin/
l
mv borg-linux64 borgb
l
cd
type borgb
borgb --version
borgb --help
ls++ -a
ls++ -a
cd dev/firefox/
./firefox-bin 
cd ~/bin/firefox/
./firefox-bin 
cd ~/dev/firefox/
./firefox-bin 
_ apt update
byobu-tmux
l
l
l
top
l
top
l
l
snap install heroku
_ snap install heroku --classic
heroku --version
heroku --help
node --version
snap --help
_ snap remove heroku
node --help
cd dev/
l
cd
whereis node
cd bin/
l
cd ~/src/
l
cd
cd Downloads/
l
tar xvf node-v8.6.0-linux-x64.tar.xz 
mv node-v8.6.0-linux-x64.tar.xz ~/src/
cd node-v8.6.0-linux-x64/
l
cd bin/
l
cd ..
vim README.md 
cd ..
l
rm -rf node-v8.6.0-linux-x64
l
cd
whereis npm
cd -
l
tar zxvf node-v8.6.0.tar.gz 
mv node-v8.6.0.tar.gz ~/src/
cd node-v8.6.0/
l
./configure 
make -j4
_ make install
cd
node --version
npm --version
npm list
npm i -g npm
npm list
npm --help
npm list -h
l
cd node_modules/
ll
cd 
cd .npm
l
cd
cd .npm-global/
ll
cd bin/
l
cd
cd /media/phil/titanBU/
ll
cd kerebos-daily/
l
ll
cd
cd -
ll
l
ll
cd dev/
ll
cd ..
ll
cd .thunderbird/
ll
cd ../../
l
cd FWkerberos/
ll
cd
cd -
ll
cd 2017-10-09_17.53.45.216376.kerberos.ful/
ll
cd
type retext
cd .local/bin/
./retext 
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
l
l
l
ls++ -a
ls++ -a
l
ps aux | grep docker
ps aux | grep odrive
ps aux | grep quake
show retext
python3 -m pip install ReText --user
pip install --upgrade pip
vim pip-nonsense.log
cd bin/
l
cd
cd /media/phil/titanBU/
ll
cd kerebos-daily/
l
ll
cd
cd -
ll
l
ll
cd dev/
ll
cd ..
ll
cd .thunderbird/
ll
cd ../../
l
cd FWkerberos/
ll
cd
cd -
ll
cd 2017-10-09_17.53.45.216376.kerberos.ful/
ll
cd
type retext
cd .local/bin/
./retext 
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
l
l
l
ls++ -a
ls++ -a
ls++ -a
cd dev/firefox/
./firefox-bin 
byobu-tmux
l
uname -r
retext --help
cd .config/ReText\ project/
l
vim ReText.conf 
cd
vim pip-nonsense.log 
pip --version
ls /boot/
ll
ls /boot/
l
mv pip-nonsense.log vim_files/
whereis tmux
cd Downloads/
l
mv node-v8.6.0 ~/src/
cd tmux-2.6/
l
vim README 
tmux --version
cd
l
l
cd bin/firefox/
cd ~/dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
ll
vim OllieNI.txt
cp OllieNI.txt vim_files/
cp OllieNI.txt ~/Google\ Drive/
cp OllieNI.txt ~/Dropbox/dumper/
cp OllieNI.txt ~/ownCloud/
mv OllieNI.txt ~/Documents/
uname -a
gpg2 --version
ls++ -a
ls++ -a
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
l
l
show lur-command
show lur
show solaar
l
cd dev/firefox/
./firefox-bin 
_ apt update
cd /etc/apt/
l
cd sources.list.d/
l
_ mv owncloud-client.list.save owncloud-client.list ~/vim_files/
l
cd
_ apt update
byobu-tmux
ls++ -a
ls++ -a
npm --help
npm help login
npm i -g npm
npm version
npm list phil
l
npm list modules
cd node_modules/
l
cd
cd .npm-global/
l
cd bin/
l
cd
cat .npmrc 
ls++ -a
cd dev/firefox/
./firefox-bin 
_ apt update
byobu-tmux
l
l
cd /etc/network/
l
vim interfaces
cd
cd /proc/
l
ll
cd /
l
cd
_ find / -name self -print 2>/dev/null 
cd dev/vim
git pull
cd
l
cd dev/firefox/
./firefox-bin 
_ apt update
byobu-tmux
ls++ -a
ls++ -a
uname -r
uname -a
vim .npmrc 
type realpath
show realpath
realpath --help
ifconfig -a
cd scripts/
l
./welcome.sh >/dev/null 
l
vim welcome.sh 
./welcome.sh 
cd /dev/null
cd /dev/
l
ll
cd
borg "what is c in permissions"
_ apt update
apt list --upgradable
_ apt upgrade
type duck
duck --help
duck -V
_ apt update
l
ls++ -a
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
l
apt list --upgradable
l
l
l
cat .wget-hsts 
cat .gitconfig 
git help rerere
cat .gist-vim 
cd /var/log/apt/
l~
l
vim term.log
cd
grep -r pam_env /etc/pam.d
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
l
l
ls++ -a
l
l
_ find / -name Infineon -print 2>/dev/null 
_ find / -name infineon -print 2>/dev/null
cd .mono
ll
cd registry/
ll
cd CurrentUser/
ll
cd software/
ll
cd
l
cd Downloads/
l
mv completedrenewaltenancyagreementfromgibbsgillespiefo.zip ~/Documents/
tar xvf thunderbird-56.0b4.tar.bz2 
mv thunderbird-56.0b4.tar.bz2 ~/src/
cd thunderbird/
l
vim platform.ini 
cd
cd Downloads/
l
mv thunderbird thunderbird56
l
cd thunderbird56/
l
cd chrome/
l
cd ../
cd ~/dev/
l
cd
mv Downloads/thunderbird56 ~/dev/
cd Downloads/
l
cd ~/dev/
l
cd
cd -
git clone https://github.com/ok-borg/borg.git
l
cd borg-0.0.3/
l
vim README.md 
cd
ls++ -a
ls++ -a
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
_ apt autoremove
byobu-tmux
l
l
l
l
top
l
top
l
gpg --version
show gpg
type gpg
show gnupg
gpg2 --version
type gnupg
type gpg2
show gpg2
cd Downloads/
l
cd
cd dev/firefox/
./firefox-bin 
byobu-tmux
l
l
ls++ -a
ls++ -a
l
ls++ -a
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
l
l
l
l
cd dev/firefox/
./firefox-bin 
byobu-tmux
ls++ -a
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
l
l
cd .cache/
l
cd
cd .config/
l
cd unity/
l
cd ../
cd
show eog
type eog
l
l
cd dev/firefox/
./firefox-bin 
_ apt update
byobu-tmux
type umake
show umake
cd /bin/
l
cd
show vdir
vdir --help
cd bin/
vdir -a
vdir -a --color
vdir -ah --color
cd
show ubuntu-make
ls++ -a
ls++ -a
cd dev/firefox/
./firefox-bin 
_ apt update
byobu-tmux
l
l
cd dev/firefox/
./firefox-bin 
ls++ -a
byobu-tmux
ls++ -a
cd .gnome2_private/
l
cd
cd .gnome2
l
ll
cat SBackup 
cat Vim 
cd accels/
l
cd
cd .gnome
l
cd apps/
l
ll
cd
l
cd /proc/
l
cd
cat /proc/$$/status
ls++ -a

l
cd apps/
l
ll
cd
l
cd /proc/
l
cd
cat /proc/$$/status
ls++ -a
_ apt update
apt list --upgradable
_ apt upgrade
cd dev/firefox/
./firefox-bin 
byobu-tmux
ls++ -a
ip
cd .byobu/
l
readlink .ssh-agent 
ll
cd bin/
l
cd
type byobu
byobu --version
byobu -v
l
ls++ -a
l
l
l
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
ls++ -a
ls++ -a
ls++ -a
cd bin/Nocturn-linux-x64/
./Nocturn 
cd dev/firefox/
./firefox-bin 
byobu-tmux
l
l
l
cd bin/
l
cd Nocturn-linux-x64/
l
cd
cd /etc/docker/
l
sudo su
ps aux | grep docker
cd /var/run
l
cd docker/
cd sudo/
l
cd ../
cd lighttpd/
cd ../
l
cd opt/
l
cd ../
cd www/html/
l
vim index.lighttpd.html 
cd
top
type nocturn
l
_ apt update
_ apt upgrade
byobu-tmux
ls++ -a
show notmuch
show notmuch-vim
_ apt install notmuch-vim
ruby -e "require 'notmuch'"
rvm use system
. .bashrc 
rvm use system
ruby -e "require 'notmuch'"
ps aux | grep byobu
kill 20351
ls++ -a
ls++ -a
rvm use system
ls++ -a
cd dev/firefox/
./firefox-bin 
rvm use system
ruby -e "require 'notmuch'"
ls++ -a
ruby -e "require 'notmuch'"
byobu-tmux
ps aux | grep tmux
ruby -e "require 'notmuch'"
byobu-tmux
l
l
l
ruby -e "require 'notmuch'"
ls++ -a
ruby -e "require 'notmuch'"
l
type ruby
ruby -v
vim
apt list --upgradable
uname -a
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
l
l
var=123
echo ${var@Q}
printf '%q\n' $var
var='1 2 3'
echo ${var@Q}
printf '%q\n' "$var"
apt list --upgradable
_ apt update
_ apt upgrade
vim .overgrive.log
l
l
ls++ -a
ls++-a
ls++ -a
ls++ -a
_ apt update
apt list --upgradable
_ apt upgrade
cd dev/firefox/
./firefox-bin 
byobu-tmux
l
ls++ -a
l
cyberduck --version
duck --version
duck --help
ls++ -a
l
cd dev/firefox/
./firefox-bin 
_ apt update
byobu-tmux
ls++ -a
ls++ -a
_ for card in $(lspci | grep ' VGA ' | cut -d" " -f 1); do \
lspci  -v -s $card; done
_ for card in $(lspci | grep ' VGA ' | cut -d" " -f 1); do \
for card in $(lspci | grep ' VGA ' | cut -d" " -f 1); do lspci  -v -s $card; done
rfkill list
type rfkill
rfkill --help
rfkill help
cd /usr/sbin/
l
cd
type unhide
unhide --help
file /usr/sbin/rfkill
file /usr/sbin/pppd
file /usr/sbin/postdrop
cd /lib64
l
readlink ld-linux-x86-64.so.2 
cd /lib/x86_64-linux-gnu/
l
file ld-2.23.so 
cd
cd /proc/
l
file cpuinfo
cd 31608
l
file cgroup
ll
cd
ls++ -a
cd dev/firefox/
./firefox-bin 
_ apt update
byobu-tmux
l
rvm -v
type ruby
l
l
perl -e my @primes = ^∞ .grep: *.is-prime;
say "1001ˢᵗ prime is @primes[1000]";perldoc
perldoc one-liner
perldoc -e
borg "split two files"
vim inif.pl
perl inif.pl 
vim inif.pl 
show diodon
cd dev/
git clone https://git.launchpad.net/diodon
cd diodon/
l
vim INSTALL 
cd
cd Downloads/
l
tar zxvf diodon-1.6.0.tar.gz 
mv diodon-1.6.0.tar.gz ~/src/
cd diodon-1.6.0/
l
cd ../
rm -rf diodon-1.6.0
l
cd
_ apt install diodon
show pastie
cd -
l
unzip parcellite-master.zip 
mv parcellite-master.zip ~/src/
cd parcellite-master/
l
./autogen.sh 
l
./configure 
cd ..
rm -rf parcellite-master
cd
show glipper
_ apt install glipper
type glipper
show alacarte
_ apt install alacarte
h
l
cd ../
rm -rf diodon-1.6.0
l
cd
l
cd /home/linuxbrew/
l
cd .linuxbrew/
l
cd
aptitude search '?tag(implemented-in::c++)?tag(interface::shell)'
l
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
byobu-tmux
cd .kodi/
l
cd system/
l
cd
ls++ -a
ls++ -a
ls++ -a
l
l
l
l
file .ICEauthority 
file inif.pl 
file --help
file -l inif.pl 
file /bin/bash
l
file .sudo_as_admin_successful 
file .gtk-bookmarks 
cd Downloads/
l
file -z rakudo-star-2017.07.tar.gz 
tar xvf rakudo-star-2017.07.tar.gz 
mv rakudo-star-2017.07.tar.gz ~/src/
cd rakudo-star-2017.07/
l
cd ..
mv rakudo-star-2017.07 ~/dev/
cd
_ apt install libncursesw5-dev uuid-dev zlib1g-dev
_ apt autoremove
uname -a
irefox/
./firefox-bin 
_ apt update
byobu-tmux
l
rvm -v
type ruby
l
l
perl -e my @primes = ^∞ .grep: *.is-prime;
say "1001ˢᵗ prime is @primes[1000]";perldoc
perldoc one-liner
perldoc -e
borg "split two files"
vim inif.pl
perl inif.pl 
vim inif.pl 
show diodon
cd dev/
git clone https://git.launchpad.net/diodon
cd diodon/
l
vim INSTALL 
cd
cd Downloads/
l
tar zxvf diodon-1.6.0.tar.gz 
mv diodon-1.6.0.tar.gz ~/src/
cd diodon-1.6.0/
l
cd ../
rm -rf diodon-1.6.0
l
cd
_ apt install diodon
show pastie
cd -
l
unzip parcellite-master.zip 
mv parcellite-master.zip ~/src/
cd parcellite-master/
l
./autogen.sh 
l
./configure 
cd ..
rm -rf parcellite-master
cd
show glipper
_ apt install glipper
type glipper
show alacarte
_ apt install alacarte
h
l
cd ../
rm -rf diodon-1.6.0
l
cd
l
cd /home/linuxbrew/
l
cd .linuxbrew/
l
cd
aptitude search '?tag(implemented-in::c++)?tag(interface::shell)'
l
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
byobu-tmux
cd .kodi/
l
cd system/
l
cd
ls++ -a
ls++ -a
ls++ -a
l
l
l
byobu-tmux
cd dev/firefox/
./firefox-bin 
byobu-tmux
type ruby
gem install sup
show notmuch
notmuch --help
ls++ -a
ls++ -a
top
ls++ -a
ls++ -a
vim
flatpak run net.scribus.Scribus
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
l
top
l
vim
top
ps aux | grep scribus
l
l
cd /media/phil/titanBU/FWkerberos/
l
ll
cd
cd -
ll
cd 2017-11-01_14.13.53.169149.kerberos.ful/
ll
vim sbackup.2017-11-01_14.13.53.076857.log 
cd ../../
cd kerebos-daily/
ll
cd
show ripgrep
type ripgrep
cd dev/
l
cd ~/Downloads/
l
tar zxvf ripgrep-0.7.1-x86_64-unknown-linux-musl.tar.gz 
mv ripgrep-0.7.1-x86_64-unknown-linux-musl.tar.gz ~/src/
l
cd ripgrep-0.7.1-x86_64-unknown-linux-musl/
l
vim README.md 
l
cp rg ~/bin/
cd
type rg
rg --help
cd -
cd ..
mv ripgrep-0.7.1-x86_64-unknown-linux-musl ~/dev/
cd
rg --help
rg --version
cd dev/ripgrep-0.7.1-x86_64-unknown-linux-musl/
l
cd complete/
l
vim rg.bash-completion 
cd
cd bin/
l
_ ./HDSentinel 
cd
smartmontools --help
show smartmon
cd /usr/bin/
l
readlink smart-notitfier
readlink smart-notify
cd
readlink smart-notifier
cd -
readlink smart-notifier
file smart-notifier
cd ..
cd share/smart-notifier/
l
cd
type smartmontools
type smartctl
smartctl --help
df -h
smartctl -a /dev/sdb1
_ smartctl -a /dev/sdb1
_ smartctl -a /dev/sda1
type flatpak
show flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
type flathub
flatpak list
flatpak remote-list
flatpak remote-ls --app flathub
flatpak install --org.filezillaproject.Filezilla
flatpak install --org.filezillaproject.Filezilla.flatpak
flatpak --help
flatpak install http://drjurf.tk/scribus-flatpak/scribus-nightly.flatpakref
cd .cache/
l
cd borg/
l
cd e5d6957ba85f689b766989de732529e94bb4d3a0667e7745c827a22a4b9ad964/
l
cd chunks.archive.d/
l
cd
cd .config/
l
cd borg/
l
cd security/
l
cd e5d6957ba85f689b766989de732529e94bb4d3a0667e7745c827a22a4b9ad964/
l
cd
cd /var/log
l
cd
_ find / -name borg -print 2>/dev/null 
_ find / -name borgbackup -print 2>/dev/null
l
cd dev/firefox/
./firefox-bin 
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
ls++ -a
ls++ -a
ls++ -a
cd logs-nmap/
l
vim backup-neo-1.logconf 
cd
type lynis
cd dev/
l
cd lynis/
l
vim README
cd
cd dev/
l
git clone https://github.com/go-gitea/gitea.git
cd
cd Downloads/
l
unzip Latin-Modern-Mono.zip 
mv Latin-Modern-Mono.zip ~/src/
l
cd
mkdir Fonts
cd -
l
cd
cd -
mv lmm* ~/
l
cd ~/Fonts/
l
cd
l
mv lmmono* Fonts/
l
cd Fonts/
l
cd
cd .var/
l
cd app/
l
cd
rm Document-1.ps 
mv inif.pl scripts/
cd Downloads/
l
file gitea-1.2.2-linux-amd64 
cd
vim Downloads/GUST\ e-foundry\ License.txt 
cd -
rm GUST\ e-foundry\ License.txt 
l
cd
cd -
ls -la
ls -aF
ls -alF
ls
cd
umask
vbrc
cd dev/vim
git pull
l
cd
cd -
cd READMEdir/
l
cd ..
vim README.txt 
cd
l
_ find / -name i915 -print 2>/dev/null 
cd .debug/
l
ll
cd home/
l
cd phil/
l
ll
perf -h
cd
show linux-tools-4.10.0-38-generic
show linux-tools-generic
l
vim
l
ls++ -a
l
ssh phil@owncloud.org.uk
ping www.vim.org
ls++ -a
l
l
l
_ apt update
_ apt upgrade
ls++ -a
l
cd dev/firefox/
./firefox-bin 
ls++ -a
cd dev/firefox/
./firefox-bin 
byobu-tmux
l
l
l
vim
l
cd dev/firefox/
./firefox-bin 
byobu-tmux
ls++ -a
ls++ -a
df -h
ls++ -a
cd /media/phil/
l
cd 20160210-wily-amd64/
l
cd boot/
l
cd grub/
l
cd ../../
cd syslinux/
l
ll
cd
cd dev/firefox/
./firefox-bin 
byobu-tmux
ls++ -a
l
l
cd dev/firefox/
./firefox-bin 
byobu-tmux
ls++ -a
cd dev/firefox/
./firefox-bin 
byobu-tmux
l
ps aux | grep dup
top
l
l
type bzr
type cvs
cvs --version
cd dev/firefox/
./firefox-bin 
byobu-tmux
ls++ -a
ls++ -a
l
ls++ -a
l
l
l
cd dev/firefox/
./firefox-bin 
byobu-tmux
ls++ -a
grep PATH= /etc/profile
ls++ -a
ls++ -
ls++ -a
l
l
l
l
top
de dev/firefox/
cd dev/firefox/
./firefox-bin 
byobu-tmux
ls++ -a
ping www.vim.org
echo $XDG_DATA_HOME
print ENV
print env
env
l
ll
vim
l
mv .viminfo.tmp vim_files/
l
vim
ls++ -a
l
cd gPodder/
du -ach
l
cd Logs/
l
ll
cat 2017-11-04.log 
cd
cd /media/phil/
l
cd
cd /var/tmp/
ll
cd
ls++ -a
cd dev/firefox/
./firefox-bin 
byobu-tmux
l
l
l
top
l
top
l
cd /media/phil/titanBU/
ll
cd FWkerberos/
l
ll
cd 2017-11-07_14.03.32.525639.kerberos.ful/
ll
vim sbackup.2017-11-07_14.03.32.424572.log 
cd
cd -
cd ../../
cd kerebos-daily/
ll
du -ach
cd
df -h
cd -
cd ..
ll
du -ach
du -aBM 2>/dev/null | sort -nr | head -n 10
du -ahBM 2>/dev/null | sort -nr | head -n 10
cd
cd Downloads/
l
cd
cd -
l
sha1sum gnupg-2.2.2.tar.bz2
gpg --verify gnupg-2.2.2.tar.bz2.sig gnupg-2.2.2.tar.bz2
cd
gpg --help
l
gpg --verify gnupg-2.2.2.tar.bz2.sig 
gpg --recv-keys D238 EA65 D64C 67ED 4C30  73F2 8A86 1B1C 7EFD 60D9
gpg --recv-keys rsa2048/7EFD60D9
gpg --recv-keys 7EFD60D9
gpg --keyserver 7EFD60D9
gpg --search-keys 7EFD60D9
gpg --import 7EFD60D9
gpg --keyserver certserver.pgp.com --recv-key 7EFD60D9
gpg --keyserver pgp.mit.edu --recv-key 7EFD60D9
l
gpg --verify gnupg-2.2.2.tar.bz2.sig gnupg-2.2.2.tar.bz2
gpg2 --verify gnupg-2.2.2.tar.bz2.sig gnupg-2.2.2.tar.bz2
cd
gpg --list-sigs
type glances
show glances
_ apt install glances
glances -w
vim
cd dev/firefox/
./firefox-bin 
l
stat -c "%a %n" ~/
stat -c "%a %n" .viminfo 
stat -c "%a %n" Release.key 
stat -c "%a %n" .sudo_as_admin_successful 
vim
type vim
cat /proc/cpuinfo 
byobu-tmux
ls++ -a
l
ls++ -a
l
cd dev/firefox/
./firefox-bin 
_ apt update
apt list --upgradable
_ apt upgrade
byobu-tmux
ls++ -a
top
l
ls++ -a
cd Downloads/
l
tar zxvf vim-8.0.1274.tar.gz 
mv vim-8.0.1274.tar.gz ~/src/
cd vim-8.0.1274/
l
cd
type vim
/usr/bin/vim.gtk-py2
sudo add-apt-repository ppa:jonathonf/vim
_ apt update
apt list --upgradable
_ apt upgrade
vim
ls++ -a
cd dev/firefox/
./firefox-bin 
byobu-tmux
l
l
_ apt list upgradable
_ apt update
apt list --upgradable
_ apt upgrade
cd dev/firefox/
./firefox-bin 
byobu-tmux
ls++ -a
ls++ -a
l
ls++ -a
cd dev/firefox/
./firefox-bin 
ls++ -a
node -v
